"""Tests for ``protean schema render --indexes``."""

from pathlib import Path

import pytest
from typer.testing import CliRunner

from protean import Index, Q
from protean.cli.schema import app, write_index_ddl
from protean.core.aggregate import BaseAggregate
from protean.fields import Integer, String

runner = CliRunner()


# A domain module written to disk for the live ``--domain`` invocation path.
_DOMAIN_MODULE = """
from protean import Domain, Index, Q

domain = Domain(name="ShopCLI")
domain.config["databases"]["default"] = {
    "provider": "sqlite",
    "database_uri": "sqlite:///:memory:",
}


@domain.aggregate(indexes=[
    Index("status", "priority", desc=("priority",),
          where=Q(status__in=["active"]), name="ix_prod_active"),
    Index("sku", unique=True),
])
class Product:
    status: str
    priority: int = 0
    sku: str
"""


class TestApplyErrors:
    def test_requires_indexes_flag(self):
        result = runner.invoke(app, ["render", "--domain=x"])
        assert result.exit_code != 0
        assert "pass --indexes" in result.output

    def test_indexes_requires_domain(self):
        result = runner.invoke(app, ["render", "--indexes"])
        assert result.exit_code != 0
        assert "requires --domain" in result.output

    def test_invalid_domain_aborts(self):
        result = runner.invoke(
            app, ["render", "--indexes", "--domain=nonexistent_module_xyz"]
        )
        assert result.exit_code != 0
        assert "Error loading Protean domain" in result.output


class TestWriteIndexDDL:
    """Direct coverage of the writer used by the command."""

    @pytest.fixture
    def shop_domain(self, test_domain):
        @test_domain.aggregate(
            indexes=[
                Index(
                    "status",
                    "priority",
                    desc=("priority",),
                    where=Q(status="active"),
                    name="ix_active",
                ),
                Index("sku", unique=True),
            ]
        )
        class Product(BaseAggregate):
            status = String(max_length=32)
            priority = Integer()
            sku = String(max_length=64)

        test_domain.init(traverse=False)
        return test_domain

    def test_writes_one_file_per_dialect(self, shop_domain, tmp_path):
        written = write_index_ddl(shop_domain, str(tmp_path), ["postgresql", "sqlite"])
        names = sorted(p.name for p in written)
        assert names == [
            "product.indexes.postgresql.sql",
            "product.indexes.sqlite.sql",
        ]

    def test_file_contains_create_index_ddl(self, shop_domain, tmp_path):
        written = write_index_ddl(shop_domain, str(tmp_path), ["postgresql"])
        assert len(written) == 1
        content = Path(written[0]).read_text(encoding="utf-8")
        assert "CREATE INDEX ix_active" in content
        assert "WHERE status = 'active'" in content
        assert "CREATE UNIQUE INDEX uq_product_sku" in content
        assert content.startswith("-- Generated by: protean schema render --indexes")

    def test_no_indexes_writes_nothing(self, test_domain, tmp_path):
        @test_domain.aggregate
        class Plain(BaseAggregate):
            name = String(max_length=32)

        test_domain.init(traverse=False)
        assert write_index_ddl(test_domain, str(tmp_path), ["sqlite"]) == []

    def test_skips_element_with_no_statements_for_dialect(self, test_domain, tmp_path):
        # Only a postgres RawIndex: rendering for sqlite yields no statements,
        # so nothing is written for that dialect.
        @test_domain.aggregate(
            indexes=[Index.from_sql("postgresql", "CREATE INDEX x ON only_a (a)")]
        )
        class OnlyA(BaseAggregate):
            a = String(max_length=10)

        test_domain.init(traverse=False)
        assert write_index_ddl(test_domain, str(tmp_path), ["sqlite"]) == []

    def test_dedups_by_schema_name_and_dialect(self, test_domain, tmp_path):
        # Two elements sharing a schema_name (as per-provider outbox clones do)
        # produce one file per (schema_name, dialect), not duplicates.
        @test_domain.aggregate(schema_name="shared", indexes=[Index("a")])
        class One(BaseAggregate):
            a = String(max_length=10)

        @test_domain.aggregate(schema_name="shared", indexes=[Index("b")])
        class Two(BaseAggregate):
            b = String(max_length=10)

        test_domain.init(traverse=False)
        written = write_index_ddl(test_domain, str(tmp_path), ["sqlite"])
        assert len(written) == 1


@pytest.mark.no_test_domain
class TestApplyCommandLive:
    def test_apply_writes_sql_files(self, tmp_path, monkeypatch):
        module = tmp_path / "shop_cli_domain.py"
        module.write_text(_DOMAIN_MODULE, encoding="utf-8")
        monkeypatch.chdir(tmp_path)
        monkeypatch.syspath_prepend(str(tmp_path))

        out = tmp_path / "out"
        result = runner.invoke(
            app,
            [
                "render",
                "--indexes",
                "--domain=shop_cli_domain",
                "--dialects=postgresql,sqlite",
                f"--output={out}",
            ],
        )
        assert result.exit_code == 0, result.output
        pg = out / "schemas" / "Product" / "product.indexes.postgresql.sql"
        assert pg.exists()
        assert "CREATE INDEX ix_prod_active" in pg.read_text(encoding="utf-8")

    def test_apply_reports_when_no_indexes(self, tmp_path, monkeypatch):
        module = tmp_path / "plain_cli_domain.py"
        module.write_text(
            "from protean import Domain\n\n"
            'domain = Domain(name="PlainCLI")\n'
            'domain.config["databases"]["default"] = {\n'
            '    "provider": "sqlite", "database_uri": "sqlite:///:memory:"}\n\n\n'
            "@domain.aggregate\n"
            "class Thing:\n"
            "    name: str\n",
            encoding="utf-8",
        )
        monkeypatch.chdir(tmp_path)
        monkeypatch.syspath_prepend(str(tmp_path))

        result = runner.invoke(
            app, ["render", "--indexes", "--domain=plain_cli_domain"]
        )
        assert result.exit_code == 0, result.output
        assert "No index declarations" in result.output
