[tool.bumpversion]
current_version = "0.13.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/protean/__init__.py"

[[tool.bumpversion.files]]
filename = "src/protean/template/domain_template/pyproject.toml.jinja"

[[tool.bumpversion.files]]
filename = "docs/guides/getting-started/installation.md"

[[tool.bumpversion.files]]
filename = "tests/test_utils.py"
