"""Tests for DomainRecord.auto_generated flag on registry elements.

Gap 2: Framework-generated elements (fact events, PM transition events,
outbox models/repos) are now tracked via auto_generated=True on DomainRecord.
"""

import pytest

from protean.core.aggregate import BaseAggregate
from protean.core.event import BaseEvent
from protean.fields import Identifier, String
from protean.utils import DomainObjects, fqn
from protean.utils.mixins import handle


# -----------------------------------------------------------------------
# Test elements
# -----------------------------------------------------------------------
class Order(BaseAggregate):
    name: String(max_length=50)


class OrderPlaced(BaseEvent):
    order_id: Identifier(identifier=True)
    name: String()


class TestAutoGeneratedOnUserElements:
    """User-declared elements should have auto_generated=False."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        test_domain.register(Order)
        test_domain.register(OrderPlaced, part_of=Order)
        test_domain.init(traverse=False)

    def test_aggregate_not_auto_generated(self, test_domain):
        record = test_domain.registry._elements[DomainObjects.AGGREGATE.value][
            fqn(Order)
        ]
        assert record.auto_generated is False

    def test_event_not_auto_generated(self, test_domain):
        record = test_domain.registry._elements[DomainObjects.EVENT.value][
            fqn(OrderPlaced)
        ]
        assert record.auto_generated is False


class TestAutoGeneratedFactEvents:
    """Fact events should be auto_generated=True but NOT internal."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        test_domain.register(Order, fact_events=True)
        test_domain.init(traverse=False)

    def test_fact_event_is_auto_generated(self, test_domain):
        event_records = test_domain.registry._elements[DomainObjects.EVENT.value]
        fact_events = {
            name: r for name, r in event_records.items() if r.cls.meta_.is_fact_event
        }
        assert len(fact_events) >= 1
        for record in fact_events.values():
            assert record.auto_generated is True

    def test_fact_event_is_not_internal(self, test_domain):
        """Fact events are publicly visible (not internal), despite being auto-generated."""
        event_records = test_domain.registry._elements[DomainObjects.EVENT.value]
        fact_events = {
            name: r for name, r in event_records.items() if r.cls.meta_.is_fact_event
        }
        for record in fact_events.values():
            assert record.internal is False

    def test_fact_event_appears_in_public_registry(self, test_domain):
        """Auto-generated fact events should appear in the public elements view."""
        all_events = test_domain.registry.elements.get("events", [])
        fact_event_classes = [cls for cls in all_events if cls.meta_.is_fact_event]
        assert len(fact_event_classes) >= 1


class TestAutoGeneratedPMTransitionEvents:
    """Process manager transition events should be auto_generated=True and internal."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        from protean.core.process_manager import BaseProcessManager
        from protean.fields import Identifier as Id

        test_domain.register(Order)
        test_domain.register(OrderPlaced, part_of=Order)

        @test_domain.process_manager(
            stream_categories=["test::order"],
        )
        class OrderProcess(BaseProcessManager):
            order_id: Id()

            @handle(OrderPlaced, start=True, correlate="order_id")
            def on_order_placed(self, event):
                self.order_id = event.order_id

        test_domain.init(traverse=False)

    def test_transition_event_is_auto_generated(self, test_domain):
        event_records = test_domain.registry._elements[DomainObjects.EVENT.value]
        transition_events = {
            name: r
            for name, r in event_records.items()
            if r.internal and "Transition" in r.name
        }
        # Process managers generate a transition event
        assert len(transition_events) >= 1
        for record in transition_events.values():
            assert record.auto_generated is True

    def test_transition_event_is_internal(self, test_domain):
        event_records = test_domain.registry._elements[DomainObjects.EVENT.value]
        transition_events = {
            name: r for name, r in event_records.items() if "Transition" in r.name
        }
        for record in transition_events.values():
            assert record.internal is True


class TestAutoGeneratedDefault:
    """Verify default value of auto_generated on DomainRecord."""

    def test_domain_record_default(self):
        from protean.domain.registry import DomainRecord

        record = DomainRecord(
            name="Test",
            qualname="test.Test",
            class_type="AGGREGATE",
            cls=Order,
        )
        assert record.auto_generated is False

    def test_domain_record_explicit_true(self):
        from protean.domain.registry import DomainRecord

        record = DomainRecord(
            name="Test",
            qualname="test.Test",
            class_type="AGGREGATE",
            cls=Order,
            auto_generated=True,
        )
        assert record.auto_generated is True
