"""Tests for _auto_generated tracking on auto-injected fields.

Gap 3: Framework-injected fields (auto id, Reference shadow fields) are now
tagged with _auto_generated=True so the IR can distinguish them from
user-declared fields.
"""

import pytest

from protean.core.aggregate import BaseAggregate
from protean.core.entity import BaseEntity
from protean.fields import HasOne, Identifier, String
from protean.fields.association import Reference
from protean.fields.spec import FieldSpec
from protean.utils.reflection import declared_fields


# -----------------------------------------------------------------------
# Test elements
# -----------------------------------------------------------------------
class Department(BaseAggregate):
    name: String(max_length=50)


class DepartmentWithCustomId(BaseAggregate):
    dept_id: Identifier(identifier=True)
    name: String(max_length=50)


class Team(BaseEntity):
    name: String(max_length=50)


class TeamWithRef(BaseEntity):
    name: String(max_length=50)
    department: Reference(Department)


class TestAutoGeneratedIdField:
    """Test that auto-injected id fields are marked _auto_generated=True."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        test_domain.register(Department)
        test_domain.register(DepartmentWithCustomId)
        test_domain.init(traverse=False)

    def test_auto_injected_id_is_auto_generated(self):
        """When no identifier is declared, framework injects id with _auto_generated=True."""
        fields = declared_fields(Department)
        id_field = fields["id"]
        assert id_field._auto_generated is True

    def test_user_declared_id_is_not_auto_generated(self):
        """When user explicitly declares an identifier, _auto_generated=False."""
        fields = declared_fields(DepartmentWithCustomId)
        id_field = fields["dept_id"]
        assert id_field._auto_generated is False

    def test_non_id_fields_not_auto_generated(self):
        """Regular user-declared fields should not be auto-generated."""
        fields = declared_fields(Department)
        name_field = fields["name"]
        assert name_field._auto_generated is False


class TestAutoGeneratedReferenceField:
    """Test that auto-created Reference shadow fields are marked _auto_generated=True."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        test_domain.register(Department)
        test_domain.register(Team, part_of=Department)
        test_domain.register(TeamWithRef, part_of=Department)
        test_domain.init(traverse=False)

    def test_auto_created_reference_is_auto_generated(self):
        """When entity has no explicit Reference, framework creates one with _auto_generated=True."""
        # Team has no explicit Reference to Department, so entity_factory creates one
        ref_field = None
        for name, field in vars(Team).items():
            if isinstance(field, Reference):
                ref_field = field
                break

        assert ref_field is not None
        assert ref_field._auto_generated is True

    def test_user_declared_reference_is_not_auto_generated(self):
        """When user explicitly declares a Reference, _auto_generated=False."""
        ref_field = None
        for name, field in vars(TeamWithRef).items():
            if isinstance(field, Reference):
                ref_field = field
                break

        assert ref_field is not None
        assert ref_field._auto_generated is False


class TestAutoGeneratedOnFieldSpec:
    """Test _auto_generated attribute on FieldSpec."""

    def test_fieldspec_default_not_auto_generated(self):
        spec = FieldSpec(str)
        assert spec._auto_generated is False

    def test_fieldspec_auto_generated_in_json_extra(self):
        """When _auto_generated is True, it appears in json_schema_extra."""
        spec = FieldSpec(str)
        spec._auto_generated = True
        kwargs = spec.resolve_field_kwargs()
        assert kwargs["json_schema_extra"]["_auto_generated"] is True

    def test_fieldspec_not_auto_generated_not_in_json_extra(self):
        """When _auto_generated is False (default), it does not appear in json_schema_extra."""
        spec = FieldSpec(str)
        kwargs = spec.resolve_field_kwargs()
        extra = kwargs.get("json_schema_extra", {})
        assert "_auto_generated" not in extra


class TestAutoGeneratedOnResolvedField:
    """Test _auto_generated extraction in ResolvedField."""

    def test_resolved_field_extracts_auto_generated(self):
        from pydantic import Field as PydanticField
        from protean.fields.resolved import ResolvedField

        finfo = PydanticField(json_schema_extra={"_auto_generated": True})
        resolved = ResolvedField("test_field", finfo, str)
        assert resolved._auto_generated is True

    def test_resolved_field_defaults_to_false(self):
        from pydantic import Field as PydanticField
        from protean.fields.resolved import ResolvedField

        finfo = PydanticField()
        resolved = ResolvedField("test_field", finfo, str)
        assert resolved._auto_generated is False

    def test_resolved_field_with_no_json_extra(self):
        from pydantic import Field as PydanticField
        from protean.fields.resolved import ResolvedField

        finfo = PydanticField()
        resolved = ResolvedField("test_field", finfo, str)
        assert resolved._auto_generated is False


class TestAutoGeneratedWithHasOneAssociation:
    """Integration test: auto-injected Reference via HasOne is _auto_generated."""

    @pytest.fixture(autouse=True)
    def register(self, test_domain):
        class Company(BaseAggregate):
            name: String(max_length=50)
            ceo: HasOne("CEO")

        class CEO(BaseEntity):
            name: String(max_length=50)

        test_domain.register(Company)
        test_domain.register(CEO, part_of=Company)
        test_domain.init(traverse=False)
        self.CEO = CEO

    def test_has_one_auto_creates_reference(self):
        """HasOne target entity gets an auto-created Reference field."""
        ref_field = None
        for name, field in vars(self.CEO).items():
            if isinstance(field, Reference):
                ref_field = field
                break

        assert ref_field is not None
        assert ref_field._auto_generated is True
