"""CLI commands for JSON Schema generation.

Usage::

    # Generate all schemas from a live domain
    protean schema generate --domain=my_app

    # Generate from an IR JSON file
    protean schema generate --ir=domain-ir.json

    # Override output directory
    protean schema generate --domain=my_app --output=build/schemas

    # Show schema for a specific element
    protean schema show OrderPlaced --domain=my_app

    # Show schema as raw JSON (for piping)
    protean schema show OrderPlaced --domain=my_app --raw
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from rich import print
from rich.console import Console
from rich.syntax import Syntax
from typing_extensions import Annotated

from protean.cli._ir_utils import load_domain, load_domain_ir, load_ir_file
from protean.ir.generators.base import short_name
from protean.utils import fully_qualified_name

app = typer.Typer(no_args_is_help=True)

_CONSOLE = Console()


@app.callback()
def callback() -> None:
    """Generate and inspect JSON Schemas for domain elements."""


# ---------------------------------------------------------------------------
# ``protean schema generate``
# ---------------------------------------------------------------------------


@app.command()
def generate(
    domain: Annotated[
        str,
        typer.Option(
            "--domain",
            "-d",
            help="Path to the domain module (e.g. 'my_app.domain')",
        ),
    ] = "",
    ir: Annotated[
        str,
        typer.Option(
            "--ir",
            help="Path to an IR JSON file",
        ),
    ] = "",
    output: Annotated[
        str,
        typer.Option(
            "--output",
            "-o",
            help="Output directory (default: .protean)",
        ),
    ] = ".protean",
) -> None:
    """Generate JSON Schema files for all data-carrying domain elements."""
    if not domain and not ir:
        print("[red]Error:[/red] provide either --domain or --ir")
        raise typer.Abort()

    if domain and ir:
        print("[red]Error:[/red] --domain and --ir are mutually exclusive")
        raise typer.Abort()

    # Load IR
    if domain:
        ir_data = load_domain_ir(domain)
    else:
        ir_data = load_ir_file(ir)

    # Write schemas and IR
    from protean.ir.generators.schema_writer import write_ir, write_schemas  # noqa: PLC0415

    written = write_schemas(ir_data, output)
    write_ir(ir_data, output)

    # Summary
    print(f"[green]Wrote {len(written)} schema files to {output}/schemas/[/green]")
    for path in written:
        print(f"  {path}")


_DEFAULT_INDEX_DIALECTS = "postgresql,sqlite,mssql"


def write_index_ddl(
    domain: Any,
    output_dir: str,
    dialects: list[str],
) -> list[Path]:
    """Render index DDL for every aggregate, entity, or projection with indexes.

    Writes one ``<schema_name>.indexes.<dialect>.sql`` file per element per
    dialect under ``<output_dir>/schemas/<cluster>/``. Returns the sorted list
    of written paths. This is the database-agnostic path: it never executes
    DDL, only renders it for review or manual application.
    """
    from protean.adapters.repository.sqlalchemy import render_index_ddl  # noqa: PLC0415

    output = Path(output_dir)
    written: list[Path] = []
    seen: set[tuple[str, str]] = set()

    registry = domain.registry
    for element_type in ("AGGREGATE", "ENTITY", "PROJECTION"):
        for record in registry._elements.get(element_type, {}).values():
            element_cls = record.cls
            declared = getattr(element_cls.meta_, "indexes", ()) or ()
            if not declared:
                continue

            schema_name = (
                element_cls.meta_.schema_name or element_cls.derive_schema_name()
            )
            cluster = short_name(fully_qualified_name(element_cls))

            for dialect in dialects:
                # Dedupe per (schema_name, dialect): per-provider clones (e.g.
                # the outbox) share a schema name and produce identical DDL.
                key = (schema_name, dialect)
                if key in seen:
                    continue
                seen.add(key)

                statements = render_index_ddl(element_cls, dialect)
                if not statements:
                    continue

                file_dir = output / "schemas" / cluster
                file_dir.mkdir(parents=True, exist_ok=True)
                file_path = file_dir / f"{schema_name}.indexes.{dialect}.sql"
                header = (
                    f"-- Generated by: protean schema render --indexes\n"
                    f"-- Element: {fully_qualified_name(element_cls)}\n"
                    f"-- Dialect: {dialect}\n\n"
                )
                body = "\n".join(f"{stmt};" for stmt in statements) + "\n"
                file_path.write_text(header + body, encoding="utf-8")
                written.append(file_path.resolve())

    return sorted(written)


@app.command()
def render(
    domain: Annotated[
        str,
        typer.Option(
            "--domain",
            "-d",
            help="Path to the domain module (e.g. 'my_app.domain')",
        ),
    ] = "",
    indexes: Annotated[
        bool,
        typer.Option(
            "--indexes",
            help="Render index DDL to .sql files",
        ),
    ] = False,
    dialects: Annotated[
        str,
        typer.Option(
            "--dialects",
            help="Comma-separated dialects (postgresql, sqlite, mssql)",
        ),
    ] = _DEFAULT_INDEX_DIALECTS,
    output: Annotated[
        str,
        typer.Option(
            "--output",
            "-o",
            help="Output directory (default: .protean)",
        ),
    ] = ".protean",
) -> None:
    """Render DDL artifacts from a live domain.

    Currently supports ``--indexes``, which writes per-dialect
    ``CREATE INDEX`` statements to ``.protean/schemas/`` for review or for
    application through your own migration tooling. Protean does not execute
    the DDL — ``protean db setup`` creates indexes on the database.
    """
    if not indexes:
        print("[red]Error:[/red] nothing to render; pass --indexes")
        raise typer.Abort()

    if not domain:
        print("[red]Error:[/red] --indexes requires --domain (live index declarations)")
        raise typer.Abort()

    dialect_list = [d.strip() for d in dialects.split(",") if d.strip()]

    live_domain = load_domain(domain)
    written = write_index_ddl(live_domain, output, dialect_list)

    if not written:
        print(
            "[yellow]No index declarations found on any aggregate, entity, "
            "or projection.[/yellow]"
        )
        return

    print(f"[green]Wrote {len(written)} index DDL files to {output}/schemas/[/green]")
    for path in written:
        print(f"  {path}")


# ---------------------------------------------------------------------------
# ``protean schema show``
# ---------------------------------------------------------------------------


@app.command()
def show(
    element: Annotated[
        str,
        typer.Argument(help="Element name or FQN to show schema for"),
    ],
    domain: Annotated[
        str,
        typer.Option(
            "--domain",
            "-d",
            help="Path to the domain module (e.g. 'my_app.domain')",
        ),
    ] = "",
    ir: Annotated[
        str,
        typer.Option(
            "--ir",
            help="Path to an IR JSON file",
        ),
    ] = "",
    raw: Annotated[
        bool,
        typer.Option(
            "--raw",
            help="Output plain JSON without syntax highlighting",
        ),
    ] = False,
) -> None:
    """Show JSON Schema for a specific domain element."""
    if not domain and not ir:
        print("[red]Error:[/red] provide either --domain or --ir")
        raise typer.Abort()

    if domain and ir:
        print("[red]Error:[/red] --domain and --ir are mutually exclusive")
        raise typer.Abort()

    # Load IR
    if domain:
        ir_data = load_domain_ir(domain)
    else:
        ir_data = load_ir_file(ir)

    # Generate all schemas
    from protean.ir.generators.schema import generate_schemas  # noqa: PLC0415

    schemas = generate_schemas(ir_data)

    # Look up element by exact FQN or short name
    schema = _resolve_element(element, schemas)

    # Output
    json_str = json.dumps(schema, indent=2, sort_keys=True)
    if raw:
        typer.echo(json_str)
    else:
        syntax = Syntax(json_str, "json", theme="monokai", word_wrap=True)
        _CONSOLE.print(syntax)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve_element(name: str, schemas: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Resolve an element by exact FQN or short name.

    If the name matches exactly as a key, return that schema.
    Otherwise, search by short name.  If multiple matches are found,
    print disambiguation options and abort.
    """
    # Exact FQN match
    if name in schemas:
        return schemas[name]

    # Short name match
    matches: list[tuple[str, dict[str, Any]]] = []
    for fqn, schema in schemas.items():
        if short_name(fqn) == name:
            matches.append((fqn, schema))

    if len(matches) == 1:
        return matches[0][1]

    if len(matches) > 1:
        print(f"[yellow]Multiple elements match '{name}':[/yellow]")
        for fqn, _ in matches:
            print(f"  {fqn}")
        print("\n[dim]Use the full FQN to disambiguate.[/dim]")
        raise typer.Abort()

    print(f"[red]Error:[/red] element '{name}' not found")
    print("\n[dim]Available elements:[/dim]")
    for fqn in sorted(schemas.keys()):
        print(f"  {fqn}")
    raise typer.Abort()
