"""Tests for correlation_id propagation through the command-processing pipeline.

Verifies that:
1. A command processed via ``domain.process()`` gets a correlation_id auto-generated.
2. Events raised by that command inherit the same correlation_id.
3. When an external correlation_id is provided, it is respected and propagated.
4. The correlation_id is stored in the event store and readable from event metadata.
"""

from uuid import uuid4

import pytest

from protean.utils.eventing import Message

from tests.tracing.elements import (
    ConfirmOrder,
    Order,
    OrderCommandHandler,
    OrderConfirmed,
    OrderPlaced,
    PlaceOrder,
    ShipOrder,
    OrderShipped,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture(autouse=True)
def register_elements(test_domain):
    test_domain.register(Order, is_event_sourced=True)
    test_domain.register(OrderPlaced, part_of=Order)
    test_domain.register(OrderConfirmed, part_of=Order)
    test_domain.register(OrderShipped, part_of=Order)
    test_domain.register(PlaceOrder, part_of=Order)
    test_domain.register(ConfirmOrder, part_of=Order)
    test_domain.register(ShipOrder, part_of=Order)
    test_domain.register(OrderCommandHandler, part_of=Order)
    test_domain.init(traverse=False)


@pytest.fixture
def order_id() -> str:
    return str(uuid4())


# ---------------------------------------------------------------------------
# Helper: read messages from the event store for a given order
# ---------------------------------------------------------------------------
def _read_events(test_domain, order_id: str) -> list[Message]:
    """Read all messages from the order's event stream."""
    stream = f"{Order.meta_.stream_category}-{order_id}"
    return test_domain.event_store.store.read(stream)


def _read_commands(test_domain, order_id: str) -> list[Message]:
    """Read all messages from the order's command stream."""
    stream = f"{Order.meta_.stream_category}:command-{order_id}"
    return test_domain.event_store.store.read(stream)


# ---------------------------------------------------------------------------
# Tests: Auto-generated correlation_id
# ---------------------------------------------------------------------------
class TestAutoGeneratedCorrelationId:
    @pytest.mark.eventstore
    def test_command_gets_auto_generated_correlation_id(self, test_domain, order_id):
        """When no correlation_id is provided, domain.process() auto-generates one."""
        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
        )

        # Read the command from the command stream
        command_stream = f"{Order.meta_.stream_category}:command-{order_id}"
        command_messages = test_domain.event_store.store.read(command_stream)
        assert len(command_messages) >= 1

        command_msg = command_messages[0]
        correlation_id = command_msg.metadata.domain.correlation_id
        assert correlation_id is not None
        assert isinstance(correlation_id, str)
        assert len(correlation_id) > 0

    @pytest.mark.eventstore
    def test_events_inherit_correlation_id_from_command(self, test_domain, order_id):
        """Events raised by a command inherit the same correlation_id."""
        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
        )

        # Read the command's correlation_id
        command_stream = f"{Order.meta_.stream_category}:command-{order_id}"
        command_messages = test_domain.event_store.store.read(command_stream)
        command_correlation_id = command_messages[0].metadata.domain.correlation_id

        # Read the event and verify it has the same correlation_id
        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 1

        event_msg = event_messages[0]
        assert event_msg.metadata.domain.correlation_id == command_correlation_id

    @pytest.mark.eventstore
    def test_multiple_events_share_same_correlation_id(self, test_domain, order_id):
        """Multiple events from the same command chain share the same correlation_id."""
        # Place and then confirm the order
        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
        )
        test_domain.process(
            ConfirmOrder(order_id=order_id),
            asynchronous=False,
        )

        # Each domain.process() call gets its own auto-generated correlation_id,
        # so the PlaceOrder and ConfirmOrder calls have different correlation_ids.
        # But events raised by each command match their command's correlation_id.
        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 2

        # Each event should have a non-None correlation_id
        for msg in event_messages:
            assert msg.metadata.domain.correlation_id is not None

    @pytest.mark.eventstore
    def test_auto_generated_correlation_ids_are_unique_across_calls(self, test_domain):
        """Each domain.process() call auto-generates a different correlation_id."""
        oid1 = str(uuid4())
        oid2 = str(uuid4())

        test_domain.process(
            PlaceOrder(order_id=oid1, customer="Alice", amount=100.0),
            asynchronous=False,
        )
        test_domain.process(
            PlaceOrder(order_id=oid2, customer="Bob", amount=200.0),
            asynchronous=False,
        )

        # Read commands
        cmd_stream1 = f"{Order.meta_.stream_category}:command-{oid1}"
        cmd_stream2 = f"{Order.meta_.stream_category}:command-{oid2}"
        cmd1 = test_domain.event_store.store.read(cmd_stream1)[0]
        cmd2 = test_domain.event_store.store.read(cmd_stream2)[0]

        # Each should have a different auto-generated correlation_id
        assert (
            cmd1.metadata.domain.correlation_id != cmd2.metadata.domain.correlation_id
        )


# ---------------------------------------------------------------------------
# Tests: External correlation_id
# ---------------------------------------------------------------------------
class TestExternalCorrelationId:
    @pytest.mark.eventstore
    def test_external_correlation_id_is_respected(self, test_domain, order_id):
        """When an explicit correlation_id is provided, it is used instead of auto-generating."""
        external_id = "ext-corr-123"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        # Verify the command stored the external correlation_id
        command_stream = f"{Order.meta_.stream_category}:command-{order_id}"
        command_messages = test_domain.event_store.store.read(command_stream)
        assert command_messages[0].metadata.domain.correlation_id == external_id

    @pytest.mark.eventstore
    def test_external_correlation_id_propagates_to_events(self, test_domain, order_id):
        """External correlation_id propagates from command to raised events."""
        external_id = "frontend-request-abc"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 1

        for msg in event_messages:
            assert msg.metadata.domain.correlation_id == external_id

    @pytest.mark.eventstore
    def test_external_correlation_id_with_multiple_commands(
        self, test_domain, order_id
    ):
        """When the same external correlation_id is used across multiple process()
        calls, all commands and events share it."""
        external_id = "session-xyz-789"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )
        test_domain.process(
            ConfirmOrder(order_id=order_id),
            asynchronous=False,
            correlation_id=external_id,
        )

        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 2

        for msg in event_messages:
            assert msg.metadata.domain.correlation_id == external_id


# ---------------------------------------------------------------------------
# Tests: Correlation ID in event store
# ---------------------------------------------------------------------------
class TestCorrelationIdInEventStore:
    @pytest.mark.eventstore
    def test_correlation_id_readable_from_message_metadata(self, test_domain, order_id):
        """The correlation_id is stored in the event store and readable
        from the deserialized Message metadata."""
        external_id = "stored-corr-456"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 1

        # Message-level metadata preserves correlation_id
        assert event_messages[0].metadata.domain.correlation_id == external_id

    @pytest.mark.eventstore
    def test_correlation_id_in_event_metadata_dict(self, test_domain, order_id):
        """Correlation ID appears in the metadata dictionary representation."""
        external_id = "dict-corr-789"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        event_messages = _read_events(test_domain, order_id)
        msg_dict = event_messages[0].to_dict()

        assert msg_dict["metadata"]["domain"]["correlation_id"] == external_id

    @pytest.mark.eventstore
    def test_correlation_id_survives_event_store_roundtrip(self, test_domain, order_id):
        """Correlation ID is preserved through write -> read at the Message level."""
        external_id = "roundtrip-corr-abc"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        # Read from the event store
        event_messages = _read_events(test_domain, order_id)
        assert len(event_messages) >= 1

        # Message level
        assert event_messages[0].metadata.domain.correlation_id == external_id

        # Dict level
        event_dict = event_messages[0].to_dict()
        assert event_dict["metadata"]["domain"]["correlation_id"] == external_id

    @pytest.mark.eventstore
    def test_command_correlation_id_survives_roundtrip(self, test_domain, order_id):
        """Command's correlation_id is preserved through event store roundtrip.

        Commands use a different _build_metadata path that preserves correlation_id
        from the incoming metadata's domain sub-object."""
        external_id = "cmd-roundtrip-xyz"

        test_domain.process(
            PlaceOrder(order_id=order_id, customer="Alice", amount=100.0),
            asynchronous=False,
            correlation_id=external_id,
        )

        command_messages = _read_commands(test_domain, order_id)
        assert len(command_messages) >= 1

        # Message level
        assert command_messages[0].metadata.domain.correlation_id == external_id

        # Dict level
        cmd_dict = command_messages[0].to_dict()
        assert cmd_dict["metadata"]["domain"]["correlation_id"] == external_id

        # Command domain objects preserve trace IDs from incoming metadata
        cmd_obj = command_messages[0].to_domain_object()
        assert cmd_obj._metadata.domain.correlation_id == external_id
