"""
Database-specific repository binding.

This example demonstrates:
- Using the database option to bind a repository to a specific database type
- Default repository uses database="ALL" (works with any database)
- Custom repository can be locked to a specific database (e.g., "postgresql", "sqlite")
- Multiple repositories per aggregate for different databases
- Database-specific query optimizations

Usage:
    # The domain automatically selects the correct repository
    # based on the provider's database type
    repo = domain.repository_for(Report)
"""

from protean import Domain
from protean.fields import Float, Identifier, String

# Domain setup
domain = Domain()


@domain.aggregate
class Report:
    """Report aggregate for analytics."""

    report_id: Identifier(identifier=True)
    title: String(required=True, max_length=200)
    report_type: String(required=True)
    generated_by: String(required=True)
    total_value: Float(default=0.0)


@domain.repository(part_of=Report)
class ReportRepository:
    """Generic repository for Report aggregate.

    This repository works with ALL databases (default behavior).
    It provides domain-specific query methods that use the standard
    DAO query interface, which works across all database providers.

    When the database option is "ALL" (default), this repository
    is used regardless of which database provider is active.
    """

    def find_by_type(self, report_type: str):
        """Find all reports of a given type."""
        return self.query.filter(report_type=report_type).all()

    def find_by_author(self, author: str):
        """Find all reports generated by a specific author."""
        return self.query.filter(generated_by=author).all()


# NOTE: Database-specific repositories are defined like this:
#
# @domain.repository(part_of=Report, database="postgresql")
# class PostgresReportRepository:
#     """PostgreSQL-specific repository for Report.
#
#     This repository is ONLY used when the provider is PostgreSQL.
#     It can contain PostgreSQL-specific optimizations like raw SQL
#     queries, materialized views, etc.
#     """
#
#     def find_by_type(self, report_type: str):
#         """Use PostgreSQL-specific query for better performance."""
#         return self.query.filter(report_type=report_type).all()
#
#     def find_high_value_reports(self, min_value: float):
#         """PostgreSQL-optimized query for high-value reports."""
#         return self.query.filter(total_value__gte=min_value).all()
#
# When the domain connects to a PostgreSQL provider, Protean automatically
# selects PostgresReportRepository instead of the generic ReportRepository.
# For any other database, the generic ReportRepository is used.


# Example usage
if __name__ == "__main__":
    domain.init(traverse=False)

    with domain.domain_context():
        repo = domain.repository_for(Report)

        # Add reports
        repo.add(
            Report(
                report_id="RPT-001",
                title="Q4 Sales Report",
                report_type="sales",
                generated_by="analyst-1",
                total_value=1250000.00,
            )
        )
        repo.add(
            Report(
                report_id="RPT-002",
                title="Monthly Expense Report",
                report_type="expenses",
                generated_by="analyst-2",
                total_value=85000.00,
            )
        )

        # Use custom queries
        sales_reports = repo.find_by_type("sales")
        print(f"Sales reports: {len(sales_reports)}")

        analyst_reports = repo.find_by_author("analyst-1")
        print(f"Reports by analyst-1: {len(analyst_reports)}")
